// Generated by the Odysseus translator 2.4.0.
// Every rule below carries the identifier it has in the specification, so the two can be
// read side by side. Do not edit: the next translation of the same specification would
// produce this file again and lose the edit.

namespace StockSharp.Odysseus.Generated;

using System;
using System.Collections.Generic;
using System.Linq;

using Ecng.Common;

using StockSharp.Algo.Indicators;
using StockSharp.Algo.Strategies;
using StockSharp.BusinessEntities;
using StockSharp.Messages;

/// <summary>Volume confirmed breakout</summary>
/// <remarks>A close above a recent high carries on when participation confirms it.</remarks>
public class Volume_confirmed_breakout : Strategy
{
	private readonly StrategyParam<int> _breakoutPeriod;
	private readonly StrategyParam<int> _volumePeriod;
	private readonly StrategyParam<decimal> _volumeMultiplier;
	private readonly StrategyParam<int> _atrPeriod;
	private readonly StrategyParam<decimal> _atrMultiplier;
	private readonly StrategyParam<DataType> _candleType;
	private readonly StrategyParam<TimeSpan> _sessionEnd;
	private readonly StrategyParam<int> _entryDelayBars;

	// The limits the specification declared. The host sizes the position from the first of
	// them, so a strategy that risks a quarter of the account and one that risks a tenth are
	// two strategies; carrying the numbers here is what makes the source say so.
	public const decimal MaxPositionPercent = 0.10m;
	public const decimal MaxDailyLossPercent = 0.02m;

	// Bars carry UTC. Every time of day in the specification is written on the clock the
	// market keeps, and the offset between the two changes twice a year, so a bar is
	// converted at the moment it arrived rather than by a fixed number of hours.
	private static readonly TimeZoneInfo _market = MarketZone();

	private AverageTrueRange _atrc7e5f8ff;
	private Highest _highesta6f045e5;
	private SimpleMovingAverage _volumeSma391a32f3;
	private Series _seriesHighesta6f045e5;

	// A signalled entry that has not been placed yet: which way, and how many candles are
	// left before it is. Zero delay never uses them.
	private int _armedSide;
	private int _armedDelay;

	// A finished candle that arrived before the clock had passed the moment it closed, kept
	// until it has.
	private ICandleMessage _heldCandle;

	private decimal _entryPrice;
	private decimal _entryVolume;
	private Sides? _entrySide;
	private int _barsHeld;
	private int _barsSeen;
	private DateTime _marketDay;
	private decimal _dayOpenPnL;

	/// <summary>BreakoutPeriod.</summary>
	public int BreakoutPeriod
	{
		get => _breakoutPeriod.Value;
		set => _breakoutPeriod.Value = value;
	}

	/// <summary>VolumePeriod.</summary>
	public int VolumePeriod
	{
		get => _volumePeriod.Value;
		set => _volumePeriod.Value = value;
	}

	/// <summary>VolumeMultiplier.</summary>
	public decimal VolumeMultiplier
	{
		get => _volumeMultiplier.Value;
		set => _volumeMultiplier.Value = value;
	}

	/// <summary>AtrPeriod.</summary>
	public int AtrPeriod
	{
		get => _atrPeriod.Value;
		set => _atrPeriod.Value = value;
	}

	/// <summary>AtrMultiplier.</summary>
	public decimal AtrMultiplier
	{
		get => _atrMultiplier.Value;
		set => _atrMultiplier.Value = value;
	}

	/// <summary>Candles the rules are evaluated on.</summary>
	public DataType CandleType
	{
		get => _candleType.Value;
		set => _candleType.Value = value;
	}

	/// <summary>Time of day the session ends, where the market is.</summary>
	public TimeSpan SessionEnd
	{
		get => _sessionEnd.Value;
		set => _sessionEnd.Value = value;
	}

	/// <summary>Candles between an entry signal and the order it produces.</summary>
	public int EntryDelayBars
	{
		get => _entryDelayBars.Value;
		set => _entryDelayBars.Value = value;
	}

	/// <summary>Declares the parameters and the ranges the optimiser may search.</summary>
	public Volume_confirmed_breakout()
	{
		_breakoutPeriod = Param(nameof(BreakoutPeriod), 20)
			.SetDisplay("BreakoutPeriod", "Declared by the specification.", "Parameters")
			.SetOptimize(10, 60, 5);

		_volumePeriod = Param(nameof(VolumePeriod), 30)
			.SetDisplay("VolumePeriod", "Declared by the specification.", "Parameters")
			.SetOptimize(10, 60, 10);

		_volumeMultiplier = Param(nameof(VolumeMultiplier), 1.5m)
			.SetDisplay("VolumeMultiplier", "Declared by the specification.", "Parameters")
			.SetOptimize(1.1m, 3.0m, 0.1m);

		_atrPeriod = Param(nameof(AtrPeriod), 14)
			.SetDisplay("AtrPeriod", "Declared by the specification.", "Parameters")
			.SetOptimize(7, 30, 1);

		_atrMultiplier = Param(nameof(AtrMultiplier), 2.0m)
			.SetDisplay("AtrMultiplier", "Declared by the specification.", "Parameters")
			.SetOptimize(1.0m, 5.0m, 0.5m);

		_candleType = Param(nameof(CandleType), TimeSpan.FromSeconds(300).TimeFrame())
			.SetDisplay("Candle type", "Candles the rules are evaluated on.", "Data");

		_sessionEnd = Param(nameof(SessionEnd), new TimeSpan(16, 0, 0))
			.SetDisplay("Session end", "Time of day the session ends, where the market is.", "Data");

		_entryDelayBars = Param(nameof(EntryDelayBars), 0)
			.SetDisplay("Entry delay", "Candles between an entry signal and the order it produces.", "Execution");
	}

	/// <summary>The market's own date for a moment, which is not the machine's.</summary>
	/// <param name="time">Moment the bar opened, in UTC.</param>
	/// <returns>The date where the market is.</returns>
	private static DateTime MarketDate(DateTime time)
		=> TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(time, DateTimeKind.Utc), _market).Date;

	/// <summary>Time of day where the market is.</summary>
	/// <param name="time">Moment the bar opened, in UTC.</param>
	/// <returns>The time of day on the market's own clock.</returns>
	private static TimeSpan MarketTime(DateTime time)
		=> TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(time, DateTimeKind.Utc), _market).TimeOfDay;

	// Both names for the same zone: the first is what every platform but Windows calls it,
	// the second is what Windows called it before it learned the first.
	private static TimeZoneInfo MarketZone()
	{
		try
		{
			return TimeZoneInfo.FindSystemTimeZoneById("America/New_York");
		}
		catch (TimeZoneNotFoundException)
		{
			return TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
		}
	}

	/// <inheritdoc />
	public override IEnumerable<(Security sec, DataType dt)> GetWorkingSecurities()
		=> [(Security, CandleType)];

	/// <inheritdoc />
	protected override void OnReseted()
	{
		base.OnReseted();
		ResetState();
	}

	/// <summary>Returns everything the rules remember between candles to its starting state.</summary>
	private void ResetState()
	{
		_heldCandle = null;
		_entryPrice = 0;
		_entryVolume = 0;
		_entrySide = null;
		_barsHeld = 0;
		_barsSeen = 0;
		_marketDay = default;
		_dayOpenPnL = 0;
		_seriesHighesta6f045e5 = new(2);
	}

	/// <inheritdoc />
	protected override void OnStarted2(DateTime time)
	{
		base.OnStarted2(time);
		ResetState();

		_atrc7e5f8ff = new AverageTrueRange { Length = AtrPeriod };
		_highesta6f045e5 = new Highest { Length = BreakoutPeriod };
		_volumeSma391a32f3 = new SimpleMovingAverage { Length = VolumePeriod };

		// The indicators are fed by hand rather than bound, because the specification chooses which
		// field each one reads and a binding always feeds the same one.
		SubscribeCandles(CandleType)
			.Bind(ProcessCandle)
			.Start();
	}

	/// <inheritdoc />
	protected override void OnOwnTradeReceived(MyTrade trade)
	{
		base.OnOwnTradeReceived(trade);

		// What the exits measure from is the price that was actually paid. An order sent after a
		// candle closes fills on the one after it, so the close of the candle the decision was made
		// on is a price this strategy never got, and a stop measured from it is placed somewhere
		// the position never was.
		var side = trade.Order.Side;
		var volume = trade.Trade.Volume;

		if (_entrySide is null)
		{
			_entrySide = side;
			_entryPrice = trade.Trade.Price;
			_entryVolume = volume;
		}
		else if (side == _entrySide && _entryVolume + volume > 0)
		{
			// A position built in more than one fill is measured from what the fills averaged.
			_entryPrice = (_entryPrice * _entryVolume + trade.Trade.Price * volume) / (_entryVolume + volume);
			_entryVolume += volume;
		}
	}

	/// <summary>Takes in a candle, and acts on it once the clock says it has closed.</summary>
	/// <param name="candle">The candle that arrived.</param>
	private void ProcessCandle(ICandleMessage candle)
	{
		if (candle.State != CandleStates.Finished)
			return;

		// A finished candle can arrive before the clock has reached the moment it closed: stored
		// history is replayed candle by candle, each one stamped with the time it opened. Acting
		// then would read a close that has not happened yet, and the order would fill inside the
		// very candle the rule was read off. A candle therefore waits until the clock has passed
		// it, which on a live feed is already true when it arrives.
		if (_heldCandle is { } held && CurrentTime >= held.CloseTime)
		{
			_heldCandle = null;
			OnCandleClosed(held);
		}

		if (CurrentTime < candle.CloseTime)
		{
			_heldCandle = candle;
			return;
		}

		OnCandleClosed(candle);
	}

	/// <summary>Decides what to do on a candle that has closed.</summary>
	/// <param name="candle">The candle that closed.</param>
	private void OnCandleClosed(ICandleMessage candle)
	{
		_atrc7e5f8ff.Process(new CandleIndicatorValue(_atrc7e5f8ff, candle) { IsFinal = true });
		var v_highesta6f045e5 = _highesta6f045e5.Process(new DecimalIndicatorValue(_highesta6f045e5, candle.HighPrice, candle.OpenTime) { IsFinal = true }).ToDecimal();
		var v_volumeSma391a32f3 = _volumeSma391a32f3.Process(new DecimalIndicatorValue(_volumeSma391a32f3, candle.TotalVolume, candle.OpenTime) { IsFinal = true }).ToDecimal();

		_seriesHighesta6f045e5.Push(v_highesta6f045e5);

		_barsSeen++;

		// The position is what says whether a trade is open, so the bookkeeping is done against it
		// rather than against the moment an order was sent.
		if (Position == 0)
		{
			_entryPrice = 0;
			_entryVolume = 0;
			_entrySide = null;
			_barsHeld = 0;
		}
		else
			_barsHeld++;

		// One order at a time. A rule that fired again while the previous order was still working
		// would send a second one for a position already on its way out.
		if (Orders.Any(o => o.State is OrderStates.Pending or OrderStates.Active))
			return;

		// A new market day starts the count again.
		var today = MarketDate(candle.OpenTime);

		if (today != _marketDay)
		{
			_marketDay = today;
			_dayOpenPnL = PnL;
		}

		// What the specification allows the day to lose, measured against the account as it
		// started rather than as it stands, so a bad run does not quietly shrink the limit.
		var dayLimit = (Portfolio?.BeginValue ?? 0m) * 0.02m;

		if (dayLimit > 0 && PnL - _dayOpenPnL <= -dayLimit)
		{
			if (Position != 0)
			{
				LogInfo("The day has lost what the specification allows it to lose; closing.");
				ClosePosition();
			}

			return;
		}

		// Nothing acts until every indicator has formed and the strategy is allowed to trade.
		// Acting earlier does not fail; it produces trades from values that were still filling up.
		// The bar count is there as well as the indicators' own readiness, and is sized for the
		// longest window the search may pick: without it a short setting would start trading
		// earlier than a long one and the two would be measured over different stretches of the
		// history, which is a difference in the data rather than in the strategy.
		if (_barsSeen < 61 || !_seriesHighesta6f045e5.Ready || !_atrc7e5f8ff.IsFormed || !_highesta6f045e5.IsFormed || !_volumeSma391a32f3.IsFormed || !IsFormedAndOnlineAndAllowTrading())
			return;

		// exits.x1: AtrStop, Long
		if (Position > 0 && (candle.ClosePrice <= _entryPrice - _atrc7e5f8ff.GetCurrentValue() * (AtrMultiplier)))
		{
			LogInfo("Exit rule x1: price moved against the position by the configured multiple of the average range.");
			SellMarket(Math.Abs(Position));
			return;
		}

		// exits.x2: SessionEnd, Long
		if (Position > 0 && (MarketTime(candle.OpenTime) >= SessionEnd))
		{
			LogInfo("Exit rule x2: the session is ending.");
			SellMarket(Math.Abs(Position));
			return;
		}

		if (_armedSide != 0)
		{
			if (--_armedDelay > 0)
				return;

			var side = _armedSide;
			_armedSide = 0;

			if (Position == 0)
			{
				LogInfo("A signalled entry is placed after the configured delay.");
				if (side > 0)
					BuyMarket(Volume);
				else
					SellMarket(Volume);
			}

			return;
		}

		// entries.e1: opens Long
		if (Position == 0 && (((candle.ClosePrice > _seriesHighesta6f045e5.At(1)) && (candle.TotalVolume > (v_volumeSma391a32f3 * VolumeMultiplier)) && (MarketTime(candle.OpenTime) >= new TimeSpan(9, 50, 0) && MarketTime(candle.OpenTime) <= new TimeSpan(15, 45, 0)))))
		{
			LogInfo("Entry rule e1 of the specification held.");

			if (EntryDelayBars > 0)
			{
				_armedSide = 1;
				_armedDelay = EntryDelayBars;
				return;
			}

			BuyMarket(Volume);
			return;
		}
	}

	/// <summary>A short window of past values, kept so that a rule can look back.</summary>
	private sealed class Series
	{
		private readonly decimal[] _values;
		private int _seen;

		/// <summary>Creates the window.</summary>
		/// <param name="size">How many values to keep.</param>
		public Series(int size)
		{
			_values = new decimal[size];
		}

		/// <summary>Whether enough values have arrived for every offset to mean something.</summary>
		public bool Ready => _seen >= _values.Length;

		/// <summary>Adds the newest value.</summary>
		/// <param name="value">Value to add.</param>
		public void Push(decimal value)
		{
			for (var i = _values.Length - 1; i > 0; i--)
				_values[i] = _values[i - 1];

			_values[0] = value;
			_seen++;
		}

		/// <summary>Reads a past value.</summary>
		/// <param name="offset">How many values back, zero being the newest.</param>
		/// <returns>The value at that offset.</returns>
		public decimal At(int offset) => _values[offset];
	}
}
