namespace Odysseus.CodeGen;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

using Odysseus.Spec;

using Odysseus.Domain;

/// <summary>
/// What translating a specification produced.
/// </summary>
/// <param name="ClassName">Name of the generated class.</param>
/// <param name="Source">The C# source.</param>
/// <param name="SourceHash">
/// What the candidate is identified by: the hash of the same source emitted without the name and the
/// thesis, so that two specifications differing only in their wording are one strategy.
/// </param>
/// <param name="Indicators">Indicators the strategy will maintain, by the field name it holds them in.</param>
public sealed record TranslatedStrategy(
	string ClassName,
	string Source,
	string SourceHash,
	IReadOnlyDictionary<string, string> Indicators);

/// <summary>
/// Turns a checked specification into a StockSharp strategy.
/// </summary>
/// <remarks>
/// The output is an ordinary <c>Strategy</c>, of the same shape as one written by hand: parameters
/// declared through <c>Param</c> with their optimisation ranges, indicators created in
/// <c>OnStarted2</c>, a candle subscription, and orders placed with <c>BuyMarket</c> and
/// <c>SellMarket</c>. That matters beyond tidiness — a candidate that survives research is then a
/// strategy anyone can take away and run in Runner, Shell or Designer, rather than something that only
/// works inside this tool.
///
/// It is a compiler rather than a generator: the same specification always produces the same source,
/// byte for byte, which is what lets a candidate be identified by the hash of its source and a result be
/// re-derived later.
///
/// The name and the thesis are written into the source because the file is meant to be read, but the
/// identity is taken over the source without them: a candidate is what it does, and rewording a
/// sentence must not spend one of the candidates a project is allowed.
/// </remarks>
public static class StrategyTranslator
{
	/// <summary>Version of the translator, which is part of what a candidate is.</summary>
	public const string Version = "2.4.0";

	// Stands in for the generated class name while the identity is being taken, so that a strategy
	// renamed is not a strategy rewritten.
	private const string IdentityClassName = "GeneratedStrategy";

	private static readonly IReadOnlyDictionary<string, string> _indicatorTypes =
		new Dictionary<string, string>(StringComparer.Ordinal)
		{
			["sma"] = "SimpleMovingAverage",
			["ema"] = "ExponentialMovingAverage",
			["rsi"] = "RelativeStrengthIndex",
			["highest"] = "Highest",
			["lowest"] = "Lowest",
			["stdDev"] = "StandardDeviation",
			["atr"] = "AverageTrueRange",
			["volumeSma"] = "SimpleMovingAverage",
		};

	/// <summary>
	/// Translates a specification.
	/// </summary>
	/// <param name="spec">Specification to translate. It must already have been checked.</param>
	/// <returns>The generated strategy.</returns>
	/// <exception cref="InvalidOperationException">The specification would not survive translation.</exception>
	public static TranslatedStrategy Translate(StrategySpec spec)
	{
		ArgumentNullException.ThrowIfNull(spec);

		var validation = SpecValidator.Validate(spec);

		if (!validation.IsValid)
		{
			// Translating an unchecked specification would turn a clear refusal into a compiler error, or
			// worse into code that runs and means something other than what was written.
			throw new InvalidOperationException(
				"Only a checked specification can be translated. Unresolved: " +
				string.Join("; ", validation.Problems.Select(p => $"{p.Path}: {p.Message}")));
		}

		var indicators = CollectIndicators(spec);
		var className = ClassNameOf(spec.Name);
		var source = Emit(spec, className, indicators, prose: true);

		// The identity is taken over the same emission with the wording left out: the class name replaced
		// by a fixed one and the two documentation lines dropped. Every rule, parameter and limit still
		// reaches the hash, so the only difference it stops seeing is the one that changes nothing.
		var identity = Emit(spec, IdentityClassName, indicators, prose: false);

		return new(
			className,
			source,
			Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(identity))),
			indicators.ToDictionary(i => i.Field, i => i.Name, StringComparer.Ordinal));
	}

	private static string Emit(
		StrategySpec spec,
		string className,
		IReadOnlyList<Indicator> indicators,
		bool prose)
	{
		var code = new CodeWriter();
		var offsets = Offsets(spec, indicators);

		code.Line($"// Generated by the Odysseus translator {Version}.");
		code.Line("// Every rule below carries the identifier it has in the specification, so the two can be");
		code.Line("// read side by side. Do not edit: the next translation of the same specification would");
		code.Line("// produce this file again and lose the edit.");
		code.Blank();
		code.Line("namespace Odysseus.Generated;");
		code.Blank();
		code.Line("using System;");
		code.Line("using System.Collections.Generic;");
		code.Line("using System.Linq;");
		code.Blank();
		code.Line("using Ecng.Common;");
		code.Blank();
		code.Line("using StockSharp.Algo.Indicators;");
		code.Line("using StockSharp.Algo.Strategies;");
		code.Line("using StockSharp.BusinessEntities;");
		code.Line("using StockSharp.Messages;");
		code.Blank();

		if (prose)
		{
			code.Line($"/// <summary>{Escape(spec.Name)}</summary>");
			code.Line($"/// <remarks>{Escape(spec.Thesis)}</remarks>");
		}

		code.Line($"public class {className} : Strategy");
		code.Open();

		EmitFields(code, spec, indicators, offsets);
		code.Blank();
		EmitProperties(code, spec);
		code.Blank();
		EmitConstructor(code, spec, className);
		code.Blank();
		EmitMarketClock(code);
		code.Blank();
		EmitWorkingSecurities(code);
		code.Blank();
		EmitReset(code, indicators, offsets);
		code.Blank();
		EmitStarted(code, indicators);
		code.Blank();
		EmitOwnTrade(code);
		code.Blank();
		EmitProcess(code, spec, indicators, offsets);

		if (offsets.Count > 0)
		{
			code.Blank();
			EmitSeries(code);
		}

		code.Close();

		return code.ToString();
	}

	private static void EmitFields(
		CodeWriter code,
		StrategySpec spec,
		IReadOnlyList<Indicator> indicators,
		IReadOnlyDictionary<string, int> offsets)
	{
		foreach (var parameter in spec.Parameters)
			code.Line($"private readonly StrategyParam<{TypeOf(parameter.Type)}> _{Camel(parameter.Name)};");

		code.Line("private readonly StrategyParam<DataType> _candleType;");
		code.Line("private readonly StrategyParam<TimeSpan> _sessionEnd;");
		code.Line("private readonly StrategyParam<int> _entryDelayBars;");
		code.Blank();

		code.Line("// The limits the specification declared. The host sizes the position from the first of");
		code.Line("// them, so a strategy that risks a quarter of the account and one that risks a tenth are");
		code.Line("// two strategies; carrying the numbers here is what makes the source say so.");
		code.Line($"public const decimal MaxPositionPercent = {Literal(spec.Risk.MaxPositionPercent, ParameterTypes.Decimal)};");
		code.Line($"public const decimal MaxDailyLossPercent = {Literal(spec.Risk.MaxDailyLossPercent, ParameterTypes.Decimal)};");
		code.Blank();

		code.Line("// Bars carry UTC. Every time of day in the specification is written on the clock the");
		code.Line("// market keeps, and the offset between the two changes twice a year, so a bar is");
		code.Line("// converted at the moment it arrived rather than by a fixed number of hours.");
		code.Line("private static readonly TimeZoneInfo _market = MarketZone();");
		code.Blank();

		foreach (var indicator in indicators)
			code.Line($"private {_indicatorTypes[indicator.Name]} {indicator.Field};");

		foreach (var (name, size) in offsets.OrderBy(o => o.Key, StringComparer.Ordinal))
			code.Line($"private Series {name};");

		code.Blank();
		code.Line("// A signalled entry that has not been placed yet: which way, and how many candles are");
		code.Line("// left before it is. Zero delay never uses them.");
		code.Line("private int _armedSide;");
		code.Line("private int _armedDelay;");
		code.Blank();
		code.Line("// A finished candle that arrived before the clock had passed the moment it closed, kept");
		code.Line("// until it has.");
		code.Line("private ICandleMessage _heldCandle;");
		code.Blank();
		code.Line("private decimal _entryPrice;");
		code.Line("private decimal _entryVolume;");
		code.Line("private Sides? _entrySide;");
		code.Line("private int _barsHeld;");
		code.Line("private int _barsSeen;");
		code.Line("private DateTime _marketDay;");
		code.Line("private decimal _dayOpenPnL;");
	}

	private static void EmitProperties(CodeWriter code, StrategySpec spec)
	{
		foreach (var parameter in spec.Parameters)
		{
			code.Line($"/// <summary>{Escape(parameter.Name)}.</summary>");
			code.Line($"public {TypeOf(parameter.Type)} {parameter.Name}");
			code.Open();
			code.Line($"get => _{Camel(parameter.Name)}.Value;");
			code.Line($"set => _{Camel(parameter.Name)}.Value = value;");
			code.Close();
			code.Blank();
		}

		code.Line("/// <summary>Candles the rules are evaluated on.</summary>");
		code.Line("public DataType CandleType");
		code.Open();
		code.Line("get => _candleType.Value;");
		code.Line("set => _candleType.Value = value;");
		code.Close();
		code.Blank();

		code.Line("/// <summary>Time of day the session ends, where the market is.</summary>");
		code.Line("public TimeSpan SessionEnd");
		code.Open();
		code.Line("get => _sessionEnd.Value;");
		code.Line("set => _sessionEnd.Value = value;");
		code.Close();
		code.Blank();

		code.Line("/// <summary>Candles between an entry signal and the order it produces.</summary>");
		code.Line("public int EntryDelayBars");
		code.Open();
		code.Line("get => _entryDelayBars.Value;");
		code.Line("set => _entryDelayBars.Value = value;");
		code.Close();
	}

	private static void EmitConstructor(CodeWriter code, StrategySpec spec, string className)
	{
		code.Line("/// <summary>Declares the parameters and the ranges the optimiser may search.</summary>");
		code.Line($"public {className}()");
		code.Open();

		foreach (var parameter in spec.Parameters)
		{
			var literal = Literal(parameter.Default, parameter.Type);

			code.Line($"_{Camel(parameter.Name)} = Param(nameof({parameter.Name}), {literal})");
			code.Indented($".SetDisplay(\"{Escape(parameter.Name)}\", \"Declared by the specification.\", \"Parameters\")");

			if (parameter.Optimizable)
			{
				code.Indented(
					$".SetOptimize({Literal(parameter.Minimum, parameter.Type)}, " +
					$"{Literal(parameter.Maximum, parameter.Type)}, {Literal(parameter.Step, parameter.Type)});");
			}
			else
			{
				code.Indented(";");
			}

			code.Blank();
		}

		code.Line($"_candleType = Param(nameof(CandleType), TimeSpan.FromSeconds({(int)spec.TimeFrame.TotalSeconds}).TimeFrame())");
		code.Indented(".SetDisplay(\"Candle type\", \"Candles the rules are evaluated on.\", \"Data\");");
		code.Blank();

		// The exchange calendar is not available to a strategy, so the close is a parameter rather than a
		// guess. Its default is the close of the American session on the clock that market keeps, which is
		// the clock every other time in the specification is written on.
		code.Line("_sessionEnd = Param(nameof(SessionEnd), new TimeSpan(16, 0, 0))");
		code.Indented(".SetDisplay(\"Session end\", \"Time of day the session ends, where the market is.\", \"Data\");");

		code.Blank();

		// Not part of the hypothesis: the rules are the same whether the fill is instant or a candle late.
		// It is here so a run can ask what the result looks like without the assumption of being fast.
		code.Line("_entryDelayBars = Param(nameof(EntryDelayBars), 0)");
		code.Indented(".SetDisplay(\"Entry delay\", \"Candles between an entry signal and the order it produces.\", \"Execution\");");

		code.Close();
	}

	private static void EmitMarketClock(CodeWriter code)
	{
		code.Line("/// <summary>The market's own date for a moment, which is not the machine's.</summary>");
		code.Line("/// <param name=\"time\">Moment the bar opened, in UTC.</param>");
		code.Line("/// <returns>The date where the market is.</returns>");
		code.Line("private static DateTime MarketDate(DateTime time)");
		code.Indented("=> TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(time, DateTimeKind.Utc), _market).Date;");
		code.Blank();

		code.Line("/// <summary>Time of day where the market is.</summary>");
		code.Line("/// <param name=\"time\">Moment the bar opened, in UTC.</param>");
		code.Line("/// <returns>The time of day on the market's own clock.</returns>");
		code.Line("private static TimeSpan MarketTime(DateTime time)");
		code.Indented("=> TimeZoneInfo.ConvertTimeFromUtc(DateTime.SpecifyKind(time, DateTimeKind.Utc), _market).TimeOfDay;");
		code.Blank();

		code.Line("// Both names for the same zone: the first is what every platform but Windows calls it,");
		code.Line("// the second is what Windows called it before it learned the first.");
		code.Line("private static TimeZoneInfo MarketZone()");
		code.Open();
		code.Line("try");
		code.Open();
		code.Line("return TimeZoneInfo.FindSystemTimeZoneById(\"America/New_York\");");
		code.Close();
		code.Line("catch (TimeZoneNotFoundException)");
		code.Open();
		code.Line("return TimeZoneInfo.FindSystemTimeZoneById(\"Eastern Standard Time\");");
		code.Close();
		code.Close();
	}

	private static void EmitWorkingSecurities(CodeWriter code)
	{
		code.Line("/// <inheritdoc />");
		code.Line("public override IEnumerable<(Security sec, DataType dt)> GetWorkingSecurities()");
		code.Indented("=> [(Security, CandleType)];");
	}

	private static void EmitReset(
		CodeWriter code,
		IReadOnlyList<Indicator> indicators,
		IReadOnlyDictionary<string, int> offsets)
	{
		code.Line("/// <inheritdoc />");
		code.Line("protected override void OnReseted()");
		code.Open();
		code.Line("base.OnReseted();");
		code.Line("ResetState();");
		code.Close();
		code.Blank();

		code.Line("/// <summary>Returns everything the rules remember between candles to its starting state.</summary>");
		code.Line("private void ResetState()");
		code.Open();
		code.Line("_heldCandle = null;");
		code.Line("_entryPrice = 0;");
		code.Line("_entryVolume = 0;");
		code.Line("_entrySide = null;");
		code.Line("_barsHeld = 0;");
		code.Line("_barsSeen = 0;");
		code.Line("_marketDay = default;");
		code.Line("_dayOpenPnL = 0;");

		foreach (var (name, size) in offsets.OrderBy(o => o.Key, StringComparer.Ordinal))
			code.Line($"{name} = new({size});");

		code.Close();
	}

	private static void EmitStarted(CodeWriter code, IReadOnlyList<Indicator> indicators)
	{
		code.Line("/// <inheritdoc />");
		code.Line("protected override void OnStarted2(DateTime time)");
		code.Open();
		code.Line("base.OnStarted2(time);");
		code.Line("ResetState();");
		code.Blank();

		foreach (var indicator in indicators)
			code.Line($"{indicator.Field} = new {_indicatorTypes[indicator.Name]} {{ Length = {indicator.LengthCode} }};");

		code.Blank();
		code.Line("// The indicators are fed by hand rather than bound, because the specification chooses which");
		code.Line("// field each one reads and a binding always feeds the same one.");
		code.Line("SubscribeCandles(CandleType)");
		code.Indented(".Bind(ProcessCandle)");
		code.Indented(".Start();");
		code.Close();
	}

	private static void EmitOwnTrade(CodeWriter code)
	{
		code.Line("/// <inheritdoc />");
		code.Line("protected override void OnOwnTradeReceived(MyTrade trade)");
		code.Open();
		code.Line("base.OnOwnTradeReceived(trade);");
		code.Blank();
		code.Line("// What the exits measure from is the price that was actually paid. An order sent after a");
		code.Line("// candle closes fills on the one after it, so the close of the candle the decision was made");
		code.Line("// on is a price this strategy never got, and a stop measured from it is placed somewhere");
		code.Line("// the position never was.");
		code.Line("var side = trade.Order.Side;");
		code.Line("var volume = trade.Trade.Volume;");
		code.Blank();
		code.Line("if (_entrySide is null)");
		code.Open();
		code.Line("_entrySide = side;");
		code.Line("_entryPrice = trade.Trade.Price;");
		code.Line("_entryVolume = volume;");
		code.Close();
		code.Line("else if (side == _entrySide && _entryVolume + volume > 0)");
		code.Open();
		code.Line("// A position built in more than one fill is measured from what the fills averaged.");
		code.Line("_entryPrice = (_entryPrice * _entryVolume + trade.Trade.Price * volume) / (_entryVolume + volume);");
		code.Line("_entryVolume += volume;");
		code.Close();
		code.Close();
	}

	/// <summary>
	/// Writes the daily loss limit, when the specification set one.
	/// </summary>
	/// <param name="code">Where the source is written.</param>
	/// <param name="spec">Specification whose risk block says what the limit is.</param>
	/// <remarks>
	/// A limit that stops the day rather than the strategy: what is open is closed and nothing further is
	/// opened until the next market day, which is what a desk does and what the specification says.
	///
	/// The day is the market's own, not the machine's - a day boundary at midnight UTC falls in the
	/// middle of the American afternoon and would reset the limit halfway through a session.
	/// </remarks>
	private static void EmitDailyLoss(CodeWriter code, StrategySpec spec)
	{
		if (spec.Risk.MaxDailyLossPercent <= 0)
			return;

		code.Line("// A new market day starts the count again.");
		code.Line("var today = MarketDate(candle.OpenTime);");
		code.Blank();
		code.Line("if (today != _marketDay)");
		code.Open();
		code.Line("_marketDay = today;");
		code.Line("_dayOpenPnL = PnL;");
		code.Close();
		code.Blank();

		code.Line("// What the specification allows the day to lose, measured against the account as it");
		code.Line("// started rather than as it stands, so a bad run does not quietly shrink the limit.");
		code.Line($"var dayLimit = (Portfolio?.BeginValue ?? 0m) * {Literal(spec.Risk.MaxDailyLossPercent, ParameterTypes.Decimal)};");
		code.Blank();

		code.Line("if (dayLimit > 0 && PnL - _dayOpenPnL <= -dayLimit)");
		code.Open();
		code.Line("if (Position != 0)");
		code.Open();
		code.Line("LogInfo(\"The day has lost what the specification allows it to lose; closing.\");");
		code.Line("ClosePosition();");
		code.Close();
		code.Blank();
		code.Line("return;");
		code.Close();
		code.Blank();
	}

	private static void EmitProcess(
		CodeWriter code,
		StrategySpec spec,
		IReadOnlyList<Indicator> indicators,
		IReadOnlyDictionary<string, int> offsets)
	{
		code.Line("/// <summary>Takes in a candle, and acts on it once the clock says it has closed.</summary>");
		code.Line("/// <param name=\"candle\">The candle that arrived.</param>");
		code.Line("private void ProcessCandle(ICandleMessage candle)");
		code.Open();
		code.Line("if (candle.State != CandleStates.Finished)");
		code.Indented("return;");
		code.Blank();
		code.Line("// A finished candle can arrive before the clock has reached the moment it closed: stored");
		code.Line("// history is replayed candle by candle, each one stamped with the time it opened. Acting");
		code.Line("// then would read a close that has not happened yet, and the order would fill inside the");
		code.Line("// very candle the rule was read off. A candle therefore waits until the clock has passed");
		code.Line("// it, which on a live feed is already true when it arrives.");
		code.Line("if (_heldCandle is { } held && CurrentTime >= held.CloseTime)");
		code.Open();
		code.Line("_heldCandle = null;");
		code.Line("OnCandleClosed(held);");
		code.Close();
		code.Blank();
		code.Line("if (CurrentTime < candle.CloseTime)");
		code.Open();
		code.Line("_heldCandle = candle;");
		code.Line("return;");
		code.Close();
		code.Blank();
		code.Line("OnCandleClosed(candle);");
		code.Close();
		code.Blank();

		code.Line("/// <summary>Decides what to do on a candle that has closed.</summary>");
		code.Line("/// <param name=\"candle\">The candle that closed.</param>");
		code.Line("private void OnCandleClosed(ICandleMessage candle)");
		code.Open();

		var read = ValuesRead(spec, indicators, offsets);

		foreach (var indicator in indicators)
		{
			// Final, because the candle was checked to be finished before anything here ran. Fed a value
			// that does not say so, an indicator treats every bar as provisional, never reports itself
			// formed, and the strategy waits for a readiness that never arrives.
			// The true range needs the whole bar and the close before it, so the average range is fed the candle.
			var process = indicator.Name == "atr"
				? $"{indicator.Field}.Process(new CandleIndicatorValue({indicator.Field}, candle) {{ IsFinal = true }})"
				: $"{indicator.Field}.Process(new DecimalIndicatorValue({indicator.Field}, {SourceOf(indicator)}, " +
					"candle.OpenTime) { IsFinal = true })";

			code.Line(read.Contains(indicator.Field)
				? $"var {indicator.Value} = {process}.ToDecimal();"
				: $"{process};");
		}

		if (indicators.Count > 0)
			code.Blank();

		foreach (var (name, _) in offsets.OrderBy(o => o.Key, StringComparer.Ordinal))
			code.Line($"{name}.Push({PushValueOf(name, indicators)});");

		if (offsets.Count > 0)
			code.Blank();

		code.Line("_barsSeen++;");
		code.Blank();

		code.Line("// The position is what says whether a trade is open, so the bookkeeping is done against it");
		code.Line("// rather than against the moment an order was sent.");
		code.Line("if (Position == 0)");
		code.Open();
		code.Line("_entryPrice = 0;");
		code.Line("_entryVolume = 0;");
		code.Line("_entrySide = null;");
		code.Line("_barsHeld = 0;");
		code.Close();
		code.Line("else");
		code.Indented("_barsHeld++;");
		code.Blank();

		code.Line("// One order at a time. A rule that fired again while the previous order was still working");
		code.Line("// would send a second one for a position already on its way out.");
		code.Line("if (Orders.Any(o => o.State is OrderStates.Pending or OrderStates.Active))");
		code.Indented("return;");
		code.Blank();

		EmitDailyLoss(code, spec);

		code.Line("// Nothing acts until every indicator has formed and the strategy is allowed to trade.");
		code.Line("// Acting earlier does not fail; it produces trades from values that were still filling up.");
		code.Line("// The bar count is there as well as the indicators' own readiness, and is sized for the");
		code.Line("// longest window the search may pick: without it a short setting would start trading");
		code.Line("// earlier than a long one and the two would be measured over different stretches of the");
		code.Line("// history, which is a difference in the data rather than in the strategy.");

		var conditions = new List<string> { $"_barsSeen < {spec.WarmupBars}" };

		conditions.AddRange(offsets.Keys.OrderBy(k => k, StringComparer.Ordinal).Select(k => $"!{k}.Ready"));
		conditions.AddRange(indicators.Select(i => $"!{i.Field}.IsFormed"));
		conditions.Add("!IsFormedAndOnlineAndAllowTrading()");

		code.Line($"if ({string.Join(" || ", conditions)})");
		code.Indented("return;");
		code.Blank();

		foreach (var exit in spec.Exits)
			EmitExit(code, spec, exit);

		EmitArmedEntry(code);

		for (var i = 0; i < spec.Entries.Count; i++)
			EmitEntry(code, spec, spec.Entries[i], last: i == spec.Entries.Count - 1);

		code.Close();
	}

	private static void EmitExit(CodeWriter code, StrategySpec spec, ExitRule exit)
	{
		var holding = exit.Direction == TradeDirections.Long ? "Position > 0" : "Position < 0";
		var close = exit.Direction == TradeDirections.Long ? "SellMarket" : "BuyMarket";

		code.Line($"// exits.{exit.Id}: {exit.Kind}, {exit.Direction}");

		var condition = exit.Kind switch
		{
			ExitKinds.Condition => Render(exit.Condition, spec),
			ExitKinds.SessionEnd => "MarketTime(candle.OpenTime) >= SessionEnd",
			ExitKinds.TimeExit => $"_barsHeld >= (int)({Render(exit.Length, spec)})",
			ExitKinds.AtrStop => RenderAtr(spec, exit, isStop: true),
			ExitKinds.AtrTarget => RenderAtr(spec, exit, isStop: false),
			_ => throw new InvalidOperationException($"There is no translation for exit kind {exit.Kind}."),
		};

		code.Line($"if ({holding} && ({condition}))");
		code.Open();
		code.Line($"LogInfo(\"{Escape(Describe(exit))}\");");
		code.Line($"{close}(Math.Abs(Position));");
		code.Line("return;");
		code.Close();
		code.Blank();
	}

	private static string RenderAtr(StrategySpec spec, ExitRule exit, bool isStop)
	{
		var field = FieldOf("atr", Render(exit.Length, spec), null);
		var distance = $"{field}.GetCurrentValue() * ({Render(exit.Multiplier, spec)})";

		return (exit.Direction, isStop) switch
		{
			(TradeDirections.Long, true) => $"candle.ClosePrice <= _entryPrice - {distance}",
			(TradeDirections.Long, false) => $"candle.ClosePrice >= _entryPrice + {distance}",
			(TradeDirections.Short, true) => $"candle.ClosePrice >= _entryPrice + {distance}",
			_ => $"candle.ClosePrice <= _entryPrice - {distance}",
		};
	}

	// An entry signalled on an earlier candle is placed here, before any new signal is looked for. It
	// exists so a run can be asked what the result looks like when the entry is not taken at the first
	// price the signal could have been acted on, which is the assumption a live account contradicts first.
	private static void EmitArmedEntry(CodeWriter code)
	{
		code.Line("if (_armedSide != 0)");
		code.Open();
		code.Line("if (--_armedDelay > 0)");
		code.Indented("return;");
		code.Blank();
		code.Line("var side = _armedSide;");
		code.Line("_armedSide = 0;");
		code.Blank();
		code.Line("if (Position == 0)");
		code.Open();
		code.Line("LogInfo(\"A signalled entry is placed after the configured delay.\");");
		code.Line("if (side > 0)");
		code.Indented("BuyMarket(Volume);");
		code.Line("else");
		code.Indented("SellMarket(Volume);");
		code.Close();
		code.Blank();
		code.Line("return;");
		code.Close();
		code.Blank();
	}

	private static void EmitEntry(CodeWriter code, StrategySpec spec, EntryRule entry, bool last)
	{
		var open = entry.Direction == TradeDirections.Long ? "BuyMarket" : "SellMarket";
		var side = entry.Direction == TradeDirections.Long ? "1" : "-1";

		code.Line($"// entries.{entry.Id}: opens {entry.Direction}");
		code.Line($"if (Position == 0 && ({Render(entry.Condition, spec)}))");
		code.Open();
		code.Line($"LogInfo(\"{Escape($"Entry rule {entry.Id} of the specification held.")}\");");
		code.Blank();
		code.Line("if (EntryDelayBars > 0)");
		code.Open();
		code.Line($"_armedSide = {side};");
		code.Line("_armedDelay = EntryDelayBars;");
		code.Line("return;");
		code.Close();
		code.Blank();
		code.Line($"{open}(Volume);");
		code.Line("return;");
		code.Close();

		if (!last)
			code.Blank();
	}

	private static string Describe(ExitRule exit)
		=> exit.Kind switch
		{
			ExitKinds.SessionEnd => $"Exit rule {exit.Id}: the session is ending.",
			ExitKinds.TimeExit => $"Exit rule {exit.Id}: the position has been held long enough.",
			ExitKinds.AtrStop => $"Exit rule {exit.Id}: price moved against the position by the configured multiple of the average range.",
			ExitKinds.AtrTarget => $"Exit rule {exit.Id}: price reached the configured multiple of the average range.",
			_ => $"Exit rule {exit.Id} of the specification held.",
		};

	/// <summary>
	/// Renders a bar count. Lengths are whole numbers of candles, and the two shapes a specification can
	/// give one in — a literal and a parameter the search varies — are both already whole, so neither
	/// needs a cast. Anything else is computed as a decimal and rounded once, here.
	/// </summary>
	private static string RenderLength(Expression expression, StrategySpec spec)
	{
		switch (expression)
		{
			case Constant node when decimal.Truncate(node.Value) == node.Value:
				return ((int)node.Value).ToString(CultureInfo.InvariantCulture);

			case ParameterRef node
				when spec.Parameters.FirstOrDefault(p => p.Name == node.Name)?.Type == ParameterTypes.Integer:
				return node.Name;

			default:
				return $"(int)({Render(expression, spec)})";
		}
	}

	private static string Render(Expression expression, StrategySpec spec)
		=> expression switch
		{
			AllOf node => node.Conditions.Count == 0
				? "true"
				: "(" + string.Join(" && ", node.Conditions.Select(c => Render(c, spec))) + ")",

			AnyOf node => node.Conditions.Count == 0
				? "false"
				: "(" + string.Join(" || ", node.Conditions.Select(c => Render(c, spec))) + ")",

			Not node => $"!({Render(node.Condition, spec)})",

			Compare node => $"({Render(node.Left, spec)} {Symbol(node.Operator)} {Render(node.Right, spec)})",

			Arithmetic node => RenderArithmetic(node, spec),

			AbsoluteValue node => $"Math.Abs({Render(node.Value, spec)})",

			Field node => node.Offset == 0
				? $"candle.{PriceOf(node.Which)}"
				: $"{SeriesOf(node.Which)}.At({node.Offset})",

			ParameterRef node => spec.Parameters.FirstOrDefault(p => p.Name == node.Name)?.Type == ParameterTypes.Decimal
				? node.Name
				: $"(decimal){node.Name}",

			Constant node => node.Value.ToString(CultureInfo.InvariantCulture) + "m",

			IndicatorRef node => RenderIndicator(node, spec),

			Cross node => RenderCross(node, spec),

			PositionIs node => node.State switch
			{
				PositionStates.Flat => "Position == 0",
				PositionStates.Long => "Position > 0",
				_ => "Position < 0",
			},

			// Written as constructed values rather than parsed text: parsing depends on the culture the
			// process runs under, and a session window meaning something else in another locale is exactly
			// the kind of result nobody can reproduce.
			SessionWindow node =>
				$"(MarketTime(candle.OpenTime) >= {Time(node.NotBefore)} && " +
				$"MarketTime(candle.OpenTime) <= {Time(node.NotAfter)})",

			_ => throw new InvalidOperationException($"There is no translation for {expression.GetType().Name}."),
		};

	private static string RenderArithmetic(Arithmetic node, StrategySpec spec)
	{
		var operands = node.Operands.Select(o => Render(o, spec)).ToArray();

		return node.Operator switch
		{
			ArithmeticOperators.Add => "(" + string.Join(" + ", operands) + ")",
			ArithmeticOperators.Subtract => "(" + string.Join(" - ", operands) + ")",
			ArithmeticOperators.Multiply => "(" + string.Join(" * ", operands) + ")",
			ArithmeticOperators.Divide => operands.Skip(1).Aggregate(operands[0], Divide),
			ArithmeticOperators.Min => operands.Aggregate((a, b) => $"Math.Min({a}, {b})"),
			_ => operands.Aggregate((a, b) => $"Math.Max({a}, {b})"),
		};
	}

	// A divisor that is a parameter can be zero on some pass of the search, and a crash halfway through a
	// run costs the whole run. The guard yields zero instead, so the pass finishes and is measured like
	// any other.
	private static string Divide(string left, string right)
		=> $"(({right}) == 0m ? 0m : ({left}) / ({right}))";

	private static string RenderIndicator(IndicatorRef node, StrategySpec spec)
	{
		var field = FieldOf(node.Name, Render(node.Length, spec), node.Source?.ToString());

		return node.Offset == 0 ? ValueOf(field) : $"{SeriesOf(field)}.At({node.Offset})";
	}

	private static string RenderCross(Cross node, StrategySpec spec)
		=> node.Direction == CrossDirections.Above
			? $"({RenderPrevious(node.Left, spec)} <= {RenderPrevious(node.Right, spec)} && {Render(node.Left, spec)} > {Render(node.Right, spec)})"
			: $"({RenderPrevious(node.Left, spec)} >= {RenderPrevious(node.Right, spec)} && {Render(node.Left, spec)} < {Render(node.Right, spec)})";

	private static string RenderPrevious(Expression expression, StrategySpec spec)
		=> expression switch
		{
			Field node => Render(node with { Offset = node.Offset + 1 }, spec),
			IndicatorRef node => Render(node with { Offset = node.Offset + 1 }, spec),
			_ => Render(expression, spec),
		};

	private static string Symbol(ComparisonOperators op)
		=> op switch
		{
			ComparisonOperators.GreaterThan => ">",
			ComparisonOperators.GreaterOrEqual => ">=",
			ComparisonOperators.LessThan => "<",
			_ => "<=",
		};

	private static string PriceOf(CandleFields field)
		=> field switch
		{
			CandleFields.Open => "OpenPrice",
			CandleFields.High => "HighPrice",
			CandleFields.Low => "LowPrice",
			CandleFields.Close => "ClosePrice",
			_ => "TotalVolume",
		};

	private static string SourceOf(Indicator indicator)
		=> indicator.Name switch
		{
			"volumeSma" => "candle.TotalVolume",
			_ => $"candle.{PriceOf(indicator.Source ?? CandleFields.Close)}",
		};

	private static IReadOnlyList<Indicator> CollectIndicators(StrategySpec spec)
	{
		var indicators = new SortedDictionary<string, Indicator>(StringComparer.Ordinal);

		void Add(string name, Expression length, CandleFields? source)
		{
			var rendered = Render(length, spec);
			var field = FieldOf(name, rendered, source?.ToString());

			indicators[field] = new(field, name, rendered, RenderLength(length, spec), source);
		}

		foreach (var expression in spec.AllExpressions)
		{
			foreach (var node in Flatten(expression).OfType<IndicatorRef>())
				Add(node.Name, node.Length, node.Source);
		}

		// The average-range exits need the indicator they are defined in terms of, even though it never
		// appears as an expression in the specification.
		foreach (var exit in spec.Exits.Where(e => e.Kind is ExitKinds.AtrStop or ExitKinds.AtrTarget))
			Add("atr", exit.Length, null);

		return [.. indicators.Values];
	}

	/// <summary>
	/// The indicators whose current value a rule actually reads. The rest are still fed every candle —
	/// an indicator that skips a candle is a different indicator — but their result goes nowhere, and an
	/// average-range exit reads the instance rather than the value.
	/// </summary>
	private static IReadOnlySet<string> ValuesRead(
		StrategySpec spec,
		IReadOnlyList<Indicator> indicators,
		IReadOnlyDictionary<string, int> offsets)
	{
		var read = new HashSet<string>(StringComparer.Ordinal);

		foreach (var expression in spec.AllExpressions)
		{
			foreach (var node in Flatten(expression).OfType<IndicatorRef>().Where(n => n.Offset == 0))
				read.Add(FieldOf(node.Name, Render(node.Length, spec), node.Source?.ToString()));
		}

		// A past value is kept by pushing the current one, so a window makes its indicator read as well.
		foreach (var indicator in indicators.Where(i => offsets.ContainsKey(SeriesOf(i.Field))))
			read.Add(indicator.Field);

		return read;
	}

	private static IReadOnlyDictionary<string, int> Offsets(StrategySpec spec, IReadOnlyList<Indicator> indicators)
	{
		var offsets = new Dictionary<string, int>(StringComparer.Ordinal);

		void Note(string series, int offset)
			=> offsets[series] = Math.Max(offsets.GetValueOrDefault(series), offset + 1);

		foreach (var expression in spec.AllExpressions)
		{
			foreach (var node in Flatten(expression))
			{
				switch (node)
				{
					case Field field when field.Offset > 0:
						Note(SeriesOf(field.Which), field.Offset);
						break;

					case IndicatorRef indicator when indicator.Offset > 0:
						Note(SeriesOf(FieldOf(indicator.Name, Render(indicator.Length, spec), indicator.Source?.ToString())), indicator.Offset);
						break;

					// A crossing compares this candle with the previous one, so both sides need one back.
					case Cross cross:
					{
						foreach (var side in new[] { cross.Left, cross.Right })
						{
							switch (side)
							{
								case Field field:
									Note(SeriesOf(field.Which), field.Offset + 1);
									break;

								case IndicatorRef indicator:
									Note(SeriesOf(FieldOf(indicator.Name, Render(indicator.Length, spec), indicator.Source?.ToString())), indicator.Offset + 1);
									break;
							}
						}

						break;
					}
				}
			}
		}

		return offsets;
	}

	private static string PushValueOf(string series, IReadOnlyList<Indicator> indicators)
	{
		foreach (var indicator in indicators)
		{
			if (SeriesOf(indicator.Field) == series)
				return indicator.Value;
		}

		foreach (var field in Enum.GetValues<CandleFields>())
		{
			if (SeriesOf(field) == series)
				return $"candle.{PriceOf(field)}";
		}

		throw new InvalidOperationException($"Nothing produces the series '{series}'.");
	}

	private static void EmitSeries(CodeWriter code)
	{
		code.Line("/// <summary>A short window of past values, kept so that a rule can look back.</summary>");
		code.Line("private sealed class Series");
		code.Open();
		code.Line("private readonly decimal[] _values;");
		code.Line("private int _seen;");
		code.Blank();
		code.Line("/// <summary>Creates the window.</summary>");
		code.Line("/// <param name=\"size\">How many values to keep.</param>");
		code.Line("public Series(int size)");
		code.Open();
		code.Line("_values = new decimal[size];");
		code.Close();
		code.Blank();
		code.Line("/// <summary>Whether enough values have arrived for every offset to mean something.</summary>");
		code.Line("public bool Ready => _seen >= _values.Length;");
		code.Blank();
		code.Line("/// <summary>Adds the newest value.</summary>");
		code.Line("/// <param name=\"value\">Value to add.</param>");
		code.Line("public void Push(decimal value)");
		code.Open();
		code.Line("for (var i = _values.Length - 1; i > 0; i--)");
		code.Indented("_values[i] = _values[i - 1];");
		code.Blank();
		code.Line("_values[0] = value;");
		code.Line("_seen++;");
		code.Close();
		code.Blank();
		code.Line("/// <summary>Reads a past value.</summary>");
		code.Line("/// <param name=\"offset\">How many values back, zero being the newest.</param>");
		code.Line("/// <returns>The value at that offset.</returns>");
		code.Line("public decimal At(int offset) => _values[offset];");
		code.Close();
	}

	private static string TypeOf(ParameterTypes type)
		=> type == ParameterTypes.Integer ? "int" : "decimal";

	private static string Literal(decimal value, ParameterTypes type)
		=> type == ParameterTypes.Integer
			? ((int)value).ToString(CultureInfo.InvariantCulture)
			: value.ToString(CultureInfo.InvariantCulture) + "m";

	private static string Time(string value)
	{
		if (!TimeSpan.TryParse(value, CultureInfo.InvariantCulture, out var time))
			throw new InvalidOperationException($"'{value}' is not a time of day.");

		return $"new TimeSpan({time.Hours}, {time.Minutes}, {time.Seconds})";
	}

	private static string FieldOf(string name, string length, string source)
	{
		// Derived from what the indicator is, so two rules asking for the same thing share one instance
		// and the strategy never computes the same series twice.
		var key = $"{name}|{length}|{source}";
		var hash = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(key)))[..8];

		return $"_{name}{hash}";
	}

	private static string ValueOf(string field)
		=> $"v{field}";

	private static string SeriesOf(string field)
		=> $"_series{char.ToUpperInvariant(field[1])}{field[2..]}";

	private static string SeriesOf(CandleFields field)
		=> $"_seriesCandle{field}";

	private static IEnumerable<Expression> Flatten(Expression expression)
	{
		yield return expression;

		foreach (var child in expression.Children)
		{
			foreach (var nested in Flatten(child))
				yield return nested;
		}
	}

	private static string Camel(string name)
		=> char.ToLowerInvariant(name[0]) + name[1..];

	private static string ClassNameOf(string name)
	{
		var text = new StringBuilder();

		foreach (var character in name)
		{
			if (char.IsLetterOrDigit(character))
				text.Append(text.Length == 0 && char.IsDigit(character) ? $"S{character}" : character);
			else if (text.Length > 0 && text[^1] != '_')
				text.Append('_');
		}

		var trimmed = text.ToString().Trim('_');

		return trimmed.Length == 0 ? "GeneratedStrategy1" : char.ToUpperInvariant(trimmed[0]) + trimmed[1..];
	}

	private static string Escape(string text)
		=> text.Replace("\\", "\\\\", StringComparison.Ordinal)
			.Replace("\"", "\\\"", StringComparison.Ordinal)
			.Replace("\r", " ", StringComparison.Ordinal)
			.Replace("\n", " ", StringComparison.Ordinal);

	private sealed record Indicator(string Field, string Name, string Length, string LengthCode, CandleFields? Source)
	{
		public string Value => ValueOf(Field);
	}
}
